[package]
name = "vpn_endpoint"
version = "0.1.0"
authors = ["Sergei Gunchenko <s.gunchenko@adguard.com>"]
edition = "2021"

[[bin]]
name = "vpn_endpoint"
path = "main.rs"

[dependencies]
vpn_libs_endpoint = { version = "0.1", path = ".." }
chrono = "0.4"
async-trait = "0.1"
log = "0.4"
md5 = "0.7"
base64 = "0.13"
serde_json = "1.0"
clap = "3.1"
sentry = { version = "0.25.0", default-features = false, features = ["backtrace", "panic", "reqwest", "rustls", "contexts"] }
