[package]
name = "vpn_libs_endpoint"
version = "0.1.0"
authors = ["Sergei Gunchenko <s.gunchenko@adguard.com>"]
edition = "2021"

[lib]
name = "vpn_libs_endpoint"
path = "src/lib.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
log = "0.4"
quiche = { version = "0.12", features = ["qlog"] }
ring = "0.16"
lazy_static = "1.4"
httparse = "1.7.1"
rustls = { version = "0.20", features = ["logging"] }
base64 = "0.13"
libc = "0.2"
tokio = { version = "1.18.0", features = ["net", "rt", "sync", "time", "macros", "rt-multi-thread"] }
h2 = "0.3"
http = "0.2"
tokio-rustls = "0.23"
rustls-pemfile = "1.0.0"
bytes = "1.1"
async-trait = "0.1"
futures = "0.3"
num_cpus = "1.13"
dynfmt = { version = "0.1", features = ["curly"], default-features = false }
serde = "1.0"
async-socks5 = "0.5"
radius = "0.2.1"
rust-crypto = "0.2.36"
md4 = "0.10.1"
des = "0.8.1"
cached = "0.34.0"
